-- MySQL Script generated by MySQL Workbench
-- lun. 28 janv. 2019 11:48:13 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wildblog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wildblog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wildblog` ;
USE `wildblog` ;

-- -----------------------------------------------------
-- Table `wildblog`.`articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wildblog`.`articles` (
  `idarticles` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `description` LONGTEXT NULL,
  `isActive` TINYINT NOT NULL,
  PRIMARY KEY (`idarticles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wildblog`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wildblog`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `role` VARCHAR(20) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `isVisible` TINYINT NOT NULL,
  `avatar` VARCHAR(100) NULL,
  `bio` LONGTEXT NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `articles_idarticles` INT NULL,
  PRIMARY KEY (`idusers`),
  INDEX `fk_users_articles1_idx` (`articles_idarticles` ASC) VISIBLE,
  CONSTRAINT `fk_users_articles1`
    FOREIGN KEY (`articles_idarticles`)
    REFERENCES `wildblog`.`articles` (`idarticles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wildblog`.`pictures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wildblog`.`pictures` (
  `idpictures` INT NOT NULL AUTO_INCREMENT,
  `link` VARCHAR(100) NOT NULL,
  `title` VARCHAR(100) NULL,
  `description` LONGTEXT NULL,
  `isActive` TINYINT NOT NULL,
  PRIMARY KEY (`idpictures`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wildblog`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wildblog`.`comments` (
  `idcomments` INT NOT NULL AUTO_INCREMENT,
  `content` LONGTEXT NOT NULL,
  `users_idusers` INT NOT NULL,
  `articles_idarticles` INT NOT NULL,
  PRIMARY KEY (`idcomments`, `users_idusers`, `articles_idarticles`),
  INDEX `fk_comments_users1_idx` (`users_idusers` ASC) VISIBLE,
  INDEX `fk_comments_articles1_idx` (`articles_idarticles` ASC) VISIBLE,
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `wildblog`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_articles1`
    FOREIGN KEY (`articles_idarticles`)
    REFERENCES `wildblog`.`articles` (`idarticles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wildblog`.`articles_has_pictures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wildblog`.`articles_has_pictures` (
  `articles_idarticles` INT NOT NULL,
  `pictures_idpictures` INT NOT NULL,
  PRIMARY KEY (`articles_idarticles`, `pictures_idpictures`),
  INDEX `fk_articles_has_pictures_pictures1_idx` (`pictures_idpictures` ASC) VISIBLE,
  INDEX `fk_articles_has_pictures_articles_idx` (`articles_idarticles` ASC) VISIBLE,
  CONSTRAINT `fk_articles_has_pictures_articles`
    FOREIGN KEY (`articles_idarticles`)
    REFERENCES `wildblog`.`articles` (`idarticles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articles_has_pictures_pictures1`
    FOREIGN KEY (`pictures_idpictures`)
    REFERENCES `wildblog`.`pictures` (`idpictures`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
